Repository ethereum/execution-spec-tests, pull requests merged in 2024-11, with the labels that each got.

#779 feat(forks): Add gas costs functions
  docs/CHANGELOG.md
  src/ethereum_test_base_types/__init__.py
  src/ethereum_test_base_types/composite_types.py
  src/ethereum_test_base_types/tests/test_base_types.py
  src/ethereum_test_fixtures/state.py
  src/ethereum_test_fixtures/tests/test_blockchain.py
  src/ethereum_test_forks/base_fork.py
  src/ethereum_test_forks/forks/forks.py
  src/ethereum_test_forks/gas_costs.py
  src/ethereum_test_forks/tests/test_forks.py
  src/ethereum_test_tools/__init__.py
  src/ethereum_test_types/__init__.py
  src/ethereum_test_types/helpers.py
  src/ethereum_test_types/tests/test_types.py
  src/ethereum_test_types/types.py
  src/pytest_plugins/execute/pre_alloc.py
  tests/cancun/eip4844_blobs/test_blob_txs.py
  tests/cancun/eip4844_blobs/test_blob_txs_full.py
  tests/cancun/eip4844_blobs/test_point_evaluation_precompile.py
  tests/cancun/eip4844_blobs/test_point_evaluation_precompile_gas.py
  tests/cancun/eip5656_mcopy/test_mcopy_memory_expansion.py
  tests/osaka/eip7692_eof_v1/eip7069_extcall/test_gas.py
  tests/osaka/eip7692_eof_v1/eip7069_extcall/test_returndatacopy_memory_expansion.py
  tests/osaka/eip7692_eof_v1/eip7480_data_section/test_datacopy_memory_expansion.py
  tests/osaka/eip7692_eof_v1/eip7620_eof_create/test_gas.py
  tests/prague/eip7702_set_code_tx/test_gas.py
  tests/shanghai/eip3860_initcode/helpers.py
  tests/shanghai/eip3860_initcode/test_initcode.py
  tests/shanghai/eip4895_withdrawals/test_withdrawals.py
Labels: scope:forks, scope:tests, type:refactor, type:feat

#917 feat(base_types): storage key hint in Storage class
  src/ethereum_test_base_types/composite_types.py
Labels: scope:pytest, type:feat

#939 fix(vm): `Bytecode` comparison
  docs/CHANGELOG.md
  src/ethereum_test_vm/bytecode.py
Labels: type:bug, scope:fw

#943 feat(clis/transition_tool): Pass `state_test` to transition tool if supported
  docs/CHANGELOG.md
  src/ethereum_clis/clis/besu.py
  src/ethereum_clis/clis/execution_specs.py
  src/ethereum_clis/transition_tool.py
  src/ethereum_test_specs/state.py
  whitelist.txt
Labels: scope:evm, type:feat

#948 new(tests): EIP-7702: Set code of non-empty-storage account
  docs/CHANGELOG.md
  src/pytest_plugins/filler/pre_alloc.py
  tests/prague/eip7702_set_code_tx/test_set_code_txs.py
Labels: scope:tests, type:test, scope:fw

#957 feat(docs): add prague-devnet-5 link; add EOF EIP links/info
  tests/osaka/eip7692_eof_v1/__init__.py
  tests/osaka/eip7692_eof_v1/eip3540_eof_v1/__init__.py
  tests/osaka/eip7692_eof_v1/eip4200_relative_jumps/__init__.py
  tests/osaka/eip7692_eof_v1/eip4750_functions/__init__.py
  tests/osaka/eip7692_eof_v1/eip5450_stack/__init__.py
  tests/osaka/eip7692_eof_v1/eip6206_jumpf/__init__.py
  tests/osaka/eip7692_eof_v1/eip663_dupn_swapn_exchange/__init__.py
  tests/osaka/eip7692_eof_v1/eip7069_extcall/__init__.py
  tests/osaka/eip7692_eof_v1/eip7480_data_section/__init__.py
  tests/osaka/eip7692_eof_v1/eip7620_eof_create/__init__.py
  tests/osaka/eip7692_eof_v1/eip7698_eof_creation_tx/__init__.py
  tests/prague/__init__.py
Labels: scope:docs, type:feat

#961 fix(fw): allow Bytecode(Opcode)
  src/ethereum_test_vm/bytecode.py
Labels: type:bug, scope:fw

#960 chore(all): bump pydantic from 2.8.2 to 2.9.2
  docs/CHANGELOG.md
  pyproject.toml
  uv.lock
Labels: scope:tests, type:chore, scope:fw

#966 fix: upgrade questionary to allow compatbility with ipython
  pyproject.toml
  uv.lock
Labels: type:chore, scope:tooling

#950 ✨ feat(et): add `et make test` for interactively creating new tests
  docs/CHANGELOG.md
  docs/writing_tests/img/et_make_test.mp4
  docs/writing_tests/index.md
  docs/writing_tests/types_of_tests.md
  pyproject.toml
  src/cli/et/__init__.py
  src/cli/et/cli.py
  src/cli/et/make/__init__.py
  src/cli/et/make/cli.py
  src/cli/et/make/commands/__init__.py
  src/cli/et/make/commands/test.py
  src/cli/et/make/templates/blockchain_test.py.j2
  src/cli/et/make/templates/state_test.py.j2
  src/cli/et/quotes.py
  src/config/docs.py
  whitelist.txt
Labels: type:feat, scope:gentest

#969 chore(fill): fix prague filling with EELS
  eels_resolutions.json
  src/pytest_plugins/forks/forks.py
  uv.lock
Labels: type:chore, scope:fill
