Repository ethereum/execution-spec-tests, pull requests merged in 2024-06, with the labels that each got.

#583 skip(tests): Lengthy EIP-2935 test
  tests/prague/eip2935_historical_block_hashes_from_state/test_block_hashes.py
Labels: scope:tests, type:chore

#572 feat(fw): add missing retesteth exceptions
  docs/CHANGELOG.md
  src/ethereum_test_tools/exceptions/exceptions.py
  whitelist.txt
Labels: type:feat, scope:fw

#594 fix(tests): EIP-7620,EIP-3540: Failing EOF tests
  tests/prague/eip7692_eof_v1/eip3540_eof_v1/container.py
  tests/prague/eip7692_eof_v1/eip3540_eof_v1/test_example_valid_invalid.py
  tests/prague/eip7692_eof_v1/eip7620_eof_create/test_eofcreate_failures.py
Labels: scope:tests, type:chore

#590 fix(tests): Pytest warning on EIP-2537 tests
  tests/prague/eip2537_bls_12_381_precompiles/helpers.py
Labels: type:bug, scope:tests

#602 feat(fw): Add `with_all_contract_creating_tx_types` marker
  docs/CHANGELOG.md
  docs/navigation.md
  docs/writing_tests/test_markers.md
  src/ethereum_test_forks/base_fork.py
  src/ethereum_test_forks/forks/forks.py
  src/ethereum_test_tools/common/types.py
  src/evm_transition_tool/evmone.py
  src/evm_transition_tool/transition_tool.py
  src/pytest_plugins/forks/forks.py
Labels: type:feat, scope:fw

#604 feat(ci): use solc-select for tox
  .github/workflows/tox_verify.yaml
  docs/CHANGELOG.md
  setup.cfg
  tox.ini
Labels: scope:ci, type:feat

#608 bug(tests): fix typos in selfdestruct test
  docs/CHANGELOG.md
  tests/cancun/eip6780_selfdestruct/test_dynamic_create2_selfdestruct_collision.py
Labels: type:bug, scope:pytest, scope:tests

#615 support coverage script for EOF tests
  .github/workflows/coverage.yaml
Labels: scope:pytest

#618 fix(ci): add solc-select to fill stage of build fixtures
  .github/actions/build-fixtures/action.yaml
Labels: type:bug, scope:ci

#596 feat(consume): enable loading of `ethereum/tests/BlockchainTests`
  docs/CHANGELOG.md
  src/cli/gen_index.py
  src/cli/hasher.py
  src/ethereum_test_tools/spec/blockchain/types.py
  whitelist.txt
Labels: type:feat, scope:consume, scope:fw

#625 feat(docs:) Add installation troubleshooting
  README.md
  docs/getting_started/installation_troubleshooting.md
  docs/getting_started/quick_start.md
  docs/navigation.md
  whitelist.txt
Labels: scope:docs

#623 refactor(fw): use pydantic PrivateAttr for model class params
  src/ethereum_test_tools/common/types.py
Labels: type:refactor, scope:fw

#584 feat(fw,tests): Add `pre.deploy_contract`, `pre.fund_eoa` methods to write tests
  docs/CHANGELOG.md
  docs/tutorials/state_transition.md
  src/ethereum_test_tools/__init__.py
  src/ethereum_test_tools/common/__init__.py
  src/ethereum_test_tools/common/base_types.py
  src/ethereum_test_tools/common/constants.py
  src/ethereum_test_tools/common/helpers.py
  src/ethereum_test_tools/common/types.py
  src/ethereum_test_tools/spec/eof/eof_test.py
  src/ethereum_test_tools/tests/test_code.py
  src/ethereum_test_tools/tests/test_filling/test_fixtures.py
  src/ethereum_test_tools/tests/test_types.py
  src/pytest_plugins/test_filler/test_filler.py
  tests/berlin/eip2930_access_list/test_acl.py
  tests/byzantium/eip198_modexp_precompile/test_modexp.py
  tests/constantinople/create2/test_recreate.py
  tests/frontier/opcodes/test_call_and_callcode_gas_calculation.py
  tests/frontier/opcodes/test_dup.py
  tests/frontier/opcodes/test_selfdestruct.py
  tests/homestead/yul/test_yul_example.py
  tests/istanbul/eip1344_chainid/test_chainid.py
  tests/prague/eip2537_bls_12_381_precompiles/conftest.py
  tests/prague/eip2537_bls_12_381_precompiles/test_bls12_g1add.py
  tests/prague/eip2537_bls_12_381_precompiles/test_bls12_g1msm.py
  tests/prague/eip2537_bls_12_381_precompiles/test_bls12_g1mul.py
  tests/prague/eip2537_bls_12_381_precompiles/test_bls12_g2add.py
  tests/prague/eip2537_bls_12_381_precompiles/test_bls12_g2msm.py
  tests/prague/eip2537_bls_12_381_precompiles/test_bls12_g2mul.py
  tests/prague/eip2537_bls_12_381_precompiles/test_bls12_map_fp2_to_g2.py
  tests/prague/eip2537_bls_12_381_precompiles/test_bls12_map_fp_to_g1.py
  tests/prague/eip2537_bls_12_381_precompiles/test_bls12_pairing.py
  tests/prague/eip2537_bls_12_381_precompiles/test_bls12_precompiles_before_fork.py
  tests/prague/eip2537_bls_12_381_precompiles/test_bls12_variable_length_input_contracts.py
  tests/prague/eip2935_historical_block_hashes_from_state/test_block_hashes.py
  tests/prague/eip6110_deposits/conftest.py
  tests/prague/eip6110_deposits/helpers.py
  tests/prague/eip6110_deposits/test_deposits.py
  tests/prague/eip7002_el_triggerable_withdrawals/conftest.py
  tests/prague/eip7002_el_triggerable_withdrawals/helpers.py
  tests/prague/eip7002_el_triggerable_withdrawals/test_withdrawal_requests.py
  tests/prague/eip7685_general_purpose_el_requests/conftest.py
  tests/prague/eip7685_general_purpose_el_requests/test_deposits_withdrawals.py
  tests/prague/eip7692_eof_v1/eip3540_eof_v1/test_calls.py
  tests/prague/eip7692_eof_v1/eip3540_eof_v1/test_code_validation.py
  tests/prague/eip7692_eof_v1/eip3540_eof_v1/test_execution_function.py
  tests/prague/eip7692_eof_v1/eip3540_eof_v1/test_extcode.py
  tests/prague/eip7692_eof_v1/eip4200_relative_jumps/test_rjumpi.py
  tests/prague/eip7692_eof_v1/eip663_dupn_swapn_exchange/conftest.py
  tests/prague/eip7692_eof_v1/eip663_dupn_swapn_exchange/test_dupn.py
  tests/prague/eip7692_eof_v1/eip663_dupn_swapn_exchange/test_exchange.py
  tests/prague/eip7692_eof_v1/eip663_dupn_swapn_exchange/test_swapn.py
  tests/prague/eip7692_eof_v1/eip7069_extcall/test_address_space_extension.py
  tests/prague/eip7692_eof_v1/eip7069_extcall/test_returndataload.py
  tests/prague/eip7692_eof_v1/eip7480_data_section/test_data_opcodes.py
  tests/prague/eip7692_eof_v1/eip7620_eof_create/helpers.py
  tests/prague/eip7692_eof_v1/eip7620_eof_create/test_eofcreate.py
  tests/prague/eip7692_eof_v1/eip7620_eof_create/test_eofcreate_failures.py
  tests/prague/eip7692_eof_v1/eip7620_eof_create/test_legacy_eof_creates.py
  whitelist.txt
Labels: scope:tests, scope:docs, type:refactor, type:feat, scope:fw

#626 fix(tests): Remove `TestAddress` usage on EOF tests
  tests/prague/eip7692_eof_v1/eip3540_eof_v1/test_calls.py
  tests/prague/eip7692_eof_v1/eip3540_eof_v1/test_code_validation.py
  tests/prague/eip7692_eof_v1/eip3540_eof_v1/test_section_order.py
Labels: scope:tests, type:chore

#620 test eof container custom_size field
  src/ethereum_test_tools/eof/v1/__init__.py
  tests/prague/eip7692_eof_v1/eip3540_eof_v1/test_example_valid_invalid.py
  tests/prague/eip7692_eof_v1/eip3540_eof_v1/test_section_size.py
Labels: scope:pytest

#627 feat(pytest): directly create properties file and release tarball from fill
  .github/actions/build-fixtures/action.yaml
  docs/CHANGELOG.md
  docs/getting_started/executing_tests_command_line.md
  src/ethereum_test_tools/spec/fixture_collector.py
  src/pytest_plugins/test_filler/test_filler.py
  src/pytest_plugins/test_filler/tests/test_test_filler.py
  whitelist.txt
Labels: scope:pytest, scope:ci

#634 new(tests): EOF - EIP-3540: test all opcodes in valid code section
  docs/CHANGELOG.md
  src/ethereum_test_tools/__init__.py
  src/ethereum_test_tools/vm/__init__.py
  src/ethereum_test_tools/vm/opcode.py
  tests/prague/eip7692_eof_v1/eip3540_eof_v1/test_all_opcodes_in_container.py
  tests/prague/eip7692_eof_v1/eip3540_eof_v1/test_example_valid_invalid.py
  whitelist.txt
Labels: scope:pytest

#628 feat(github): coverage on native evmone test runners
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/coverage.yaml
Labels: type:feat

#638 fix(plugins): Root folder name in generated .tar.gz
  src/pytest_plugins/test_filler/test_filler.py
Labels: type:bug

#641 fix(plugins/forks): remove `pytest.skip` from pytest_generate_tests
  src/pytest_plugins/forks/forks.py
Labels: type:bug, type:chore

#643 feat: coverage script check file existance in tests
  .github/workflows/coverage.yaml
Labels: type:feat

#644 fix(github,configs): Temporarily disable `tox -e tests-develop`, update geth evm
  .github/workflows/tox_verify.yaml
  configs/evm.yaml
Labels: type:chore

#600 fix(fw,tests): Withdrawal request v1 update execution-apis #549
  docs/CHANGELOG.md
  src/ethereum_test_tools/common/types.py
  tests/prague/eip7002_el_triggerable_withdrawals/helpers.py
  tests/prague/eip7002_el_triggerable_withdrawals/test_withdrawal_requests.py
  tests/prague/eip7685_general_purpose_el_requests/test_deposits_withdrawals.py
Labels: scope:tests, type:chore, type:refactor, scope:fw

#585 new(tests): EIP-2935 - Update tests to recent spec change
  docs/CHANGELOG.md
  setup.cfg
  src/ethereum_test_forks/forks/contracts/deposit_contract.bin
  src/ethereum_test_forks/forks/contracts/history_contract.bin
  src/ethereum_test_forks/forks/contracts/withdrawal_request.bin
  src/ethereum_test_forks/forks/forks.py
  src/ethereum_test_forks/forks/history_contract.bin
  src/ethereum_test_tools/common/types.py
  tests/prague/eip2935_historical_block_hashes_from_state/spec.py
  tests/prague/eip2935_historical_block_hashes_from_state/test_block_hashes.py
  whitelist.txt
Labels: scope:tests, type:test

#648 feat(vm): Opcode keyword arguments
  docs/CHANGELOG.md
  src/ethereum_test_tools/tests/test_vm.py
  src/ethereum_test_tools/vm/opcode.py
Labels: type:feat, scope:fw

#651 feat(fw): EOF - Add `containerKind` to EOF fixtures, add `--initcode` flag when calling evmone-eofparse
  docs/CHANGELOG.md
  src/ethereum_test_tools/eof/v1/__init__.py
  src/ethereum_test_tools/spec/eof/eof_test.py
  src/ethereum_test_tools/spec/eof/types.py
Labels: scope:fw
