Repository ethereum/execution-spec-tests, pull requests merged in 2024-04, with the labels that each got.

#480 chore(forks): generate fixtures with the Paris network name
  docs/CHANGELOG.md
  src/ethereum_test_forks/forks/forks.py
  src/ethereum_test_forks/tests/test_forks.py
  src/ethereum_test_tools/tests/test_filling/fixtures/chainid_paris_blockchain_test_hive.json
  src/ethereum_test_tools/tests/test_filling/fixtures/chainid_paris_state_test.json
Labels: scope:forks, type:chore

#483 feat: port entry points to click cli; add tests
  docs/CHANGELOG.md
  docs/getting_started/executing_tests_command_line.md
  setup.cfg
  src/cli/evm_bytes_to_python.py
  src/cli/hasher.py
  src/cli/order_fixtures.py
  src/cli/pytest_commands.py
  src/cli/tests/__init__.py
  src/cli/tests/test_evm_bytes_to_python.py
  src/cli/tests/test_order_fixtures.py
  src/cli/tests/test_pytest_commands.py
  src/cli/tox_helpers.py
  src/entry_points/fill.py
  src/entry_points/markdownlintcli2_soft_fail.py
  src/entry_points/pyspelling_soft_fail.py
  src/entry_points/tests/__init__.py
  src/entry_points/tf.py
  src/pytest_plugins/test_help/test_help.py
  tox.ini
  whitelist.txt
Labels: type:feat, scope:fw

#493 chore: remove repetitive words
  docs/writing_tests/code_standards.md
  docs/writing_tests/exception_tests.md
Labels: type:chore

#486 feat/pydantic: Use Pydantic library for types
  docs/CHANGELOG.md
  pyproject.toml
  setup.cfg
  src/ethereum_test_tools/__init__.py
  src/ethereum_test_tools/common/__init__.py
  src/ethereum_test_tools/common/base_types.py
  src/ethereum_test_tools/common/json.py
  src/ethereum_test_tools/common/types.py
  src/ethereum_test_tools/exceptions/__init__.py
  src/ethereum_test_tools/exceptions/exceptions.py
  src/ethereum_test_tools/spec/__init__.py
  src/ethereum_test_tools/spec/base/base_test.py
  src/ethereum_test_tools/spec/blockchain/blockchain_test.py
  src/ethereum_test_tools/spec/blockchain/types.py
  src/ethereum_test_tools/spec/fixture_collector.py
  src/ethereum_test_tools/spec/state/state_test.py
  src/ethereum_test_tools/spec/state/types.py
  src/ethereum_test_tools/tests/test_code.py
  src/ethereum_test_tools/tests/test_exceptions.py
  src/ethereum_test_tools/tests/test_filling/test_expect.py
  src/ethereum_test_tools/tests/test_filling/test_fixtures.py
  src/ethereum_test_tools/tests/test_specs.py
  src/ethereum_test_tools/tests/test_transactions.py
  src/ethereum_test_tools/tests/test_types.py
  src/ethereum_test_tools/tests/test_types_blockchain_test.py
  src/evm_transition_tool/besu.py
  src/evm_transition_tool/tests/test_evaluate.py
  src/evm_transition_tool/transition_tool.py
  src/pytest_plugins/forks/tests/test_forks.py
  src/pytest_plugins/test_filler/test_filler.py
  tests/cancun/eip4788_beacon_root/conftest.py
  tests/cancun/eip4788_beacon_root/test_beacon_root_contract.py
  tests/cancun/eip4844_blobs/test_blob_txs.py
  tests/cancun/eip4844_blobs/test_blob_txs_full.py
  tests/cancun/eip4844_blobs/test_blobhash_opcode.py
  tests/cancun/eip4844_blobs/test_blobhash_opcode_contexts.py
  tests/cancun/eip4844_blobs/test_excess_blob_gas.py
  tests/cancun/eip4844_blobs/test_excess_blob_gas_fork_transition.py
  tests/cancun/eip6780_selfdestruct/test_dynamic_create2_selfdestruct_collision.py
  tests/cancun/eip6780_selfdestruct/test_reentrancy_selfdestruct_revert.py
  tests/cancun/eip6780_selfdestruct/test_selfdestruct.py
  tests/cancun/eip6780_selfdestruct/test_selfdestruct_revert.py
  tests/cancun/eip7516_blobgasfee/test_blobgasfee_opcode.py
  tests/istanbul/eip1344_chainid/test_chainid.py
  tests/shanghai/eip3651_warm_coinbase/test_warm_coinbase.py
  tests/shanghai/eip4895_withdrawals/test_withdrawals.py
  whitelist.txt
Labels: scope:tools, scope:pytest, scope:tests, type:refactor, type:feat, scope:fw

#491 fix(tests): mcopy: block gas limit for memory expansion tests
  tests/cancun/eip5656_mcopy/test_mcopy_memory_expansion.py
Labels: scope:tests, type:chore

#492 feat(fw): Parameter count check on opcode calls
  docs/CHANGELOG.md
  src/ethereum_test_tools/tests/test_vm.py
  src/ethereum_test_tools/vm/opcode.py
  tests/cancun/eip1153_tstore/test_tstorage_execution_contexts.py
  tests/shanghai/eip3860_initcode/test_initcode.py
Labels: scope:tests, type:feat, scope:fw

#489 all: Mark Cancun fork as deployed
  .github/workflows/fixtures.yaml
  .vscode/launch.recommended.json
  .vscode/settings.recommended.json
  docs/CHANGELOG.md
  docs/consuming_tests/index.md
  src/ethereum_test_forks/forks/forks.py
  src/ethereum_test_forks/tests/test_forks.py
  src/ethereum_test_tools/code/__init__.py
  src/ethereum_test_tools/code/yul.py
  src/ethereum_test_tools/tests/conftest.py
  src/ethereum_test_tools/tests/test_code.py
  src/pytest_plugins/test_filler/test_filler.py
  tox.ini
Labels: scope:evm, scope:forks, scope:docs, scope:ci, type:chore

#490 test(fw): add empty account tests
  src/ethereum_test_tools/common/types.py
  src/ethereum_test_tools/tests/test_types.py
Labels: type:bug, scope:fw

#501 feat(fw): add pydantic models for json fixture files
  docs/CHANGELOG.md
  setup.cfg
  src/cli/__init__.py
  src/cli/check_fixtures.py
  src/cli/tests/test_evm_bytes_to_python.py
  src/cli/tests/test_order_fixtures.py
  src/cli/tests/test_pytest_commands.py
  src/ethereum_test_tools/common/json.py
  src/ethereum_test_tools/common/types.py
  src/ethereum_test_tools/exceptions/__init__.py
  src/ethereum_test_tools/exceptions/exceptions.py
  src/ethereum_test_tools/spec/base/base_test.py
  src/ethereum_test_tools/spec/blockchain/types.py
  src/ethereum_test_tools/spec/file/__init__.py
  src/ethereum_test_tools/spec/file/types.py
  src/ethereum_test_tools/spec/state/types.py
  src/ethereum_test_tools/tests/test_exceptions.py
  src/ethereum_test_tools/tests/test_filling/fixtures/blockchain_london_invalid_filled.json
  src/ethereum_test_tools/tests/test_filling/fixtures/blockchain_london_valid_filled.json
  src/ethereum_test_tools/tests/test_filling/fixtures/blockchain_shanghai_invalid_filled_hive.json
  src/ethereum_test_tools/tests/test_filling/fixtures/blockchain_shanghai_valid_filled_hive.json
  src/ethereum_test_tools/tests/test_filling/fixtures/chainid_istanbul_blockchain_test.json
  src/ethereum_test_tools/tests/test_filling/fixtures/chainid_london_blockchain_test.json
  src/ethereum_test_tools/tests/test_filling/fixtures/chainid_paris_blockchain_test_hive.json
  src/ethereum_test_tools/tests/test_filling/fixtures/chainid_paris_state_test.json
  src/ethereum_test_tools/tests/test_filling/fixtures/chainid_shanghai_blockchain_test_hive.json
  src/ethereum_test_tools/tests/test_filling/fixtures/chainid_shanghai_state_test.json
  src/ethereum_test_tools/tests/test_filling/test_fixtures.py
  src/ethereum_test_tools/tests/test_spec_base.py
  src/ethereum_test_tools/tests/test_types.py
  whitelist.txt
Labels: type:feat, scope:fw

#508 refactor(fw): augment & use Fixtures model in fixture collection
  docs/CHANGELOG.md
  src/ethereum_test_tools/spec/base/base_test.py
  src/ethereum_test_tools/spec/file/types.py
  src/ethereum_test_tools/spec/fixture_collector.py
Labels: type:refactor, scope:fw

#510 chore: soften package requirements for compatibility with other dependences
  docs/CHANGELOG.md
  setup.cfg
Labels: type:bug, scope:ci, type:chore

#515 chore(ci): disable tox -e tests-develop in github actions
  .github/workflows/fixtures.yaml
  .github/workflows/test.yaml
Labels: scope:ci, type:chore

#512 feat(fw): EOF support
  docs/CHANGELOG.md
  docs/consuming_tests/eof_test.md
  docs/navigation.md
  src/cli/tests/test_evm_bytes_to_python.py
  src/ethereum_test_tools/__init__.py
  src/ethereum_test_tools/common/__init__.py
  src/ethereum_test_tools/common/helpers.py
  src/ethereum_test_tools/eof/__init__.py
  src/ethereum_test_tools/eof/constants.py
  src/ethereum_test_tools/eof/v1/__init__.py
  src/ethereum_test_tools/eof/v1/constants.py
  src/ethereum_test_tools/exceptions/__init__.py
  src/ethereum_test_tools/exceptions/exceptions.py
  src/ethereum_test_tools/spec/__init__.py
  src/ethereum_test_tools/spec/base/base_test.py
  src/ethereum_test_tools/spec/eof/__init__.py
  src/ethereum_test_tools/spec/eof/eof_test.py
  src/ethereum_test_tools/spec/eof/types.py
  src/ethereum_test_tools/tests/test_eof_v1.py
  src/ethereum_test_tools/tests/test_vm.py
  src/ethereum_test_tools/vm/opcode.py
  src/evm_transition_tool/transition_tool.py
  tests/prague/eip3540_eof_v1/__init__.py
  tests/prague/eip3540_eof_v1/code_validation.py
  tests/prague/eip3540_eof_v1/code_validation_function.py
  tests/prague/eip3540_eof_v1/code_validation_jump.py
  tests/prague/eip3540_eof_v1/container.py
  tests/prague/eip3540_eof_v1/opcodes.py
  tests/prague/eip3540_eof_v1/spec.py
  tests/prague/eip3540_eof_v1/test_code_validation.py
  tests/prague/eip3540_eof_v1/test_eof_example.py
  tests/prague/eip3540_eof_v1/test_execution_function.py
  tests/shanghai/eip3860_initcode/test_initcode.py
  whitelist.txt
Labels: scope:pytest, scope:tests, type:refactor, type:feat, scope:fw

#520 chore(ci): hotfix github actions by using macos-12
  .github/workflows/test.yaml
Labels: type:bug, scope:ci

#524 fix github workflow
  .github/workflows/test.yaml
Labels: type:bug

#525 chore(ci): Revert CI to use macOS and Ubuntu latest releases
  .github/workflows/test.yaml
  tox.ini
Labels: scope:ci, type:chore
