Repository ethereum/execution-spec-tests, pull requests merged in 2024-03, with the labels that each got.

#463 docs(chore): remove extra '|' in table to appease markdownlint-cli2 v0.12.1
  docs/consuming_tests/index.md
Labels: scope:docs, type:chore

#454 feat(fw): Add sha256 hash to fixtures
  docs/CHANGELOG.md
  docs/writing_tests/verifying_changes.md
  setup.cfg
  src/entry_points/hasher.py
  src/ethereum_test_tools/common/json.py
  src/ethereum_test_tools/spec/base/base_test.py
  src/ethereum_test_tools/spec/blockchain/types.py
  src/ethereum_test_tools/spec/state/types.py
  src/ethereum_test_tools/tests/test_filling/fixtures/blockchain_london_invalid_filled.json
  src/ethereum_test_tools/tests/test_filling/fixtures/blockchain_london_valid_filled.json
  src/ethereum_test_tools/tests/test_filling/fixtures/blockchain_shanghai_invalid_filled_hive.json
  src/ethereum_test_tools/tests/test_filling/fixtures/blockchain_shanghai_valid_filled_hive.json
  src/ethereum_test_tools/tests/test_filling/fixtures/chainid_istanbul_blockchain_test.json
  src/ethereum_test_tools/tests/test_filling/fixtures/chainid_london_blockchain_test.json
  src/ethereum_test_tools/tests/test_filling/fixtures/chainid_paris_blockchain_test_hive.json
  src/ethereum_test_tools/tests/test_filling/fixtures/chainid_paris_state_test.json
  src/ethereum_test_tools/tests/test_filling/fixtures/chainid_shanghai_blockchain_test_hive.json
  src/ethereum_test_tools/tests/test_filling/fixtures/chainid_shanghai_state_test.json
  src/ethereum_test_tools/tests/test_filling/test_fixtures.py
  whitelist.txt
Labels: scope:tests, type:feat, scope:fw

#449 fix(tests): Remove beacon root contract from state tests
  docs/CHANGELOG.md
  src/ethereum_test_forks/base_fork.py
  src/ethereum_test_forks/forks/forks.py
  src/ethereum_test_forks/tests/test_forks.py
  src/ethereum_test_tools/spec/blockchain/blockchain_test.py
  src/ethereum_test_tools/spec/state/state_test.py
  tests/cancun/eip4788_beacon_root/test_beacon_root_contract.py
  tests/cancun/eip4788_beacon_root/test_blocks_beacon_root_contract.py
Labels: scope:tests, type:chore, scope:fw

#431 feat(fw): add optional `verify_sync` flag to hive blockchain tests
  docs/CHANGELOG.md
  src/ethereum_test_tools/spec/blockchain/blockchain_test.py
  src/ethereum_test_tools/spec/blockchain/types.py
  whitelist.txt
Labels: type:feat, hive, scope:fw

#472 bug(fw): fix block header `gasLimit` value in post genesis blocks for blockchain tests
  docs/CHANGELOG.md
  src/ethereum_test_tools/spec/blockchain/types.py
Labels: type:bug, scope:fw

#473 docs: update changelog for post release v2.1.1
  docs/CHANGELOG.md
Labels: scope:docs

#477 fix(fw): Fix `FixedSizeBytes` `!=` comparison
  docs/CHANGELOG.md
  src/ethereum_test_tools/common/base_types.py
  src/ethereum_test_tools/tests/test_base_types.py
Labels: type:bug, scope:fw

#484 fix: bump go version from 1.20.5 to 1.21.x
  .github/actions/build-geth-evm/action.yaml
  docs/CHANGELOG.md
  whitelist.txt
Labels: type:bug, scope:ci

#457 feat(tests): extend Op with Op.OOG macro opcode
  docs/CHANGELOG.md
  src/entry_points/evm_bytes_to_python.py
  src/entry_points/tests/test_evm_bytes_to_python.py
  src/ethereum_test_tools/__init__.py
  src/ethereum_test_tools/tests/test_vm.py
  src/ethereum_test_tools/vm/__init__.py
  src/ethereum_test_tools/vm/opcode.py
  whitelist.txt
Labels: scope:pytest
