Repository ethereum/execution-spec-tests, pull requests merged in 2024-07, with the labels that each got.

#660 fix(fw): Tox
  src/ethereum_test_tools/common/types.py
  src/ethereum_test_tools/spec/consume/types.py
  src/ethereum_test_tools/tests/test_exceptions.py
Labels: type:bug, scope:fw

#657 fix(github): Coverage script on remote repo
  .github/workflows/coverage.yaml
Labels: type:test

#440 feat(tests): EIP-1153: Convert tests from `ethereum/tests`
  converted-ethereum-tests.txt
  docs/CHANGELOG.md
  src/ethereum_test_tools/vm/opcode.py
  tests/cancun/eip1153_tstore/test_basic_tload.py
  tests/cancun/eip1153_tstore/test_tload_calls.py
  tests/cancun/eip1153_tstore/test_tload_reentrancy.py
  tests/cancun/eip1153_tstore/test_tstore_reentrancy.py
  tests/homestead/coverage/__init__.py
  tests/homestead/coverage/test_coverage.py
Labels: scope:pytest, scope:tests, type:test

#632 fix(fw): EVM binary pattern for windows
  README.md
  src/evm_transition_tool/geth.py
Labels: scope:fw

#666 fix(tests): EOF - EIP-4200: Organize code_validation_jump.py tests
  docs/CHANGELOG.md
  src/ethereum_test_tools/exceptions/evmone_exceptions.py
  src/ethereum_test_tools/exceptions/exceptions.py
  src/ethereum_test_tools/vm/opcode.py
  tests/prague/eip7692_eof_v1/eip3540_eof_v1/code_validation_jump.py
  tests/prague/eip7692_eof_v1/eip4200_relative_jumps/test_rjump.py
  tests/prague/eip7692_eof_v1/eip4200_relative_jumps/test_rjumpi.py
  tests/prague/eip7692_eof_v1/eip4200_relative_jumps/test_rjumpv.py
Labels: scope:tests

#663 fix(setup): Pin pydantic minor version
  setup.cfg
  src/ethereum_test_tools/common/types.py
  src/ethereum_test_tools/spec/consume/types.py
Labels: type:chore, scope:fw

#679 fix(fw): Fix `CopyValidateModel`
  src/ethereum_test_tools/common/types.py
  src/ethereum_test_tools/tests/test_types.py
Labels: type:bug

#688 fix(evm_transition_tool): Remove evmone empty-to-string workaround
  src/evm_transition_tool/evmone.py
  src/evm_transition_tool/transition_tool.py
  src/evm_transition_tool/types.py
Labels: type:chore

#691 feat(consume): add consume engine hive simulator
  docs/CHANGELOG.md
  pytest-consume.ini
  pytest-framework.ini
  setup.cfg
  src/cli/gen_index.py
  src/cli/gentest.py
  src/cli/pytest_commands.py
  src/ethereum_test_fixtures/__init__.py
  src/ethereum_test_fixtures/blockchain.py
  src/ethereum_test_specs/blockchain.py
  src/ethereum_test_specs/tests/fixtures/blockchain_shanghai_invalid_filled_hive.json
  src/ethereum_test_specs/tests/fixtures/blockchain_shanghai_valid_filled_hive.json
  src/ethereum_test_specs/tests/fixtures/chainid_paris_blockchain_test_hive.json
  src/ethereum_test_specs/tests/fixtures/chainid_shanghai_blockchain_test_hive.json
  src/ethereum_test_tools/rpc/__init__.py
  src/ethereum_test_tools/rpc/rpc.py
  src/ethereum_test_tools/rpc/types.py
  src/ethereum_test_tools/tests/test_filling/fixtures/blockchain_shanghai_invalid_filled_hive.json
  src/pytest_plugins/consume/direct/conftest.py
  src/pytest_plugins/consume/direct/test_direct.py
  src/pytest_plugins/consume/engine.py
  src/pytest_plugins/consume/hive_rulest_engine.py
  src/pytest_plugins/consume/hive_simulators/conftest.py
  src/pytest_plugins/consume/hive_simulators/engine/conftest.py
  src/pytest_plugins/consume/hive_simulators/engine/test_via_engine.py
  src/pytest_plugins/consume/hive_simulators/exceptions.py
  src/pytest_plugins/consume/hive_simulators/rlp/conftest.py
  src/pytest_plugins/consume/hive_simulators/rlp/test_via_rlp.py
  src/pytest_plugins/consume/hive_simulators/ruleset.py
  src/pytest_plugins/consume/ini_files/pytest-consume-all.ini
  src/pytest_plugins/consume/ini_files/pytest-consume-direct.ini
  src/pytest_plugins/consume/ini_files/pytest-consume-engine.ini
  src/pytest_plugins/consume/ini_files/pytest-consume-rlp.ini
  src/pytest_plugins/consume/rlp.py
  src/pytest_plugins/consume/simulator_common.py
  tests_consume/test_via_engine_api.py
  tests_consume/test_via_rlp.py
  tox.ini
  whitelist.txt
Labels: type:feat, scope:consume, scope:fw

#694 chore(fw): remove old custom logger
  src/logger.cfg
  src/logger.py
Labels: type:chore

#692 refactor(plugins): Move pre-alloc logic to a separate filler plugin, rename test_filler
  docs/library/pytest_plugins/filler.md
  docs/library/pytest_plugins/navigation.md
  docs/library/pytest_plugins/test_filler.md
  docs/navigation.md
  pytest-consume.ini
  pytest-framework.ini
  pytest.ini
  src/cli/tests/test_pytest_commands.py
  src/ethereum_test_specs/tests/test_fixtures.py
  src/ethereum_test_tools/tests/test_code.py
  src/ethereum_test_types/tests/test_types.py
  src/ethereum_test_types/types.py
  src/pytest_plugins/filler/__init__.py
  src/pytest_plugins/filler/filler.py
  src/pytest_plugins/filler/pre_alloc.py
  src/pytest_plugins/filler/tests/__init__.py
  src/pytest_plugins/filler/tests/test_filler.py
  src/pytest_plugins/filler/tests/test_pre_alloc.py
  src/pytest_plugins/help/__init__.py
  src/pytest_plugins/help/help.py
  src/pytest_plugins/help/tests/test_help.py
Labels: type:refactor

#697 chore(docs): v3.0.0 changelog
  docs/CHANGELOG.md
Labels: type:chore

#698 chore(tools/rpc): Improve RPC typing
  src/cli/gentest.py
  src/ethereum_test_tools/rpc/rpc.py
  src/ethereum_test_tools/rpc/types.py
  src/ethereum_test_types/types.py
Labels: type:chore, scope:fw

#497 new(tests): EIP-1014: Convert CREATE2 test from `ethereum/tests`
  converted-ethereum-tests.txt
  docs/CHANGELOG.md
  tests/constantinople/eip1014_create2/__init__.py
  tests/constantinople/eip1014_create2/spec.py
  tests/constantinople/eip1014_create2/test_create_returndata.py
  tests/constantinople/eip1014_create2/test_recreate.py
  tests/homestead/coverage/test_coverage.py
Labels: scope:tests, type:test

#702 chore(pytest): fix gen index plugin UI for engine tests
  src/cli/gen_index.py
Labels: scope:pytest, type:chore

#701 chore(consume): fix `--input` when running from hive
  docs/CHANGELOG.md
  src/cli/pytest_commands.py
  whitelist.txt
Labels: type:chore, scope:consume

#700 fix(specs,transition_tool): Trace dump fixes
  src/ethereum_test_specs/eof.py
  src/evm_transition_tool/transition_tool.py
Labels: type:bug

#621 new(tests): EIP-7702 - Set EOA account code for one transaction (Devnet-1)
  docs/CHANGELOG.md
  src/ethereum_test_base_types/composite_types.py
  src/ethereum_test_fixtures/blockchain.py
  src/ethereum_test_fixtures/state.py
  src/ethereum_test_fixtures/tests/test_blockchain.py
  src/ethereum_test_tools/__init__.py
  src/ethereum_test_types/__init__.py
  src/ethereum_test_types/types.py
  tests/prague/eip7702_eoa_code_tx/__init__.py
  tests/prague/eip7702_eoa_code_tx/spec.py
  tests/prague/eip7702_eoa_code_tx/test_eoa_code_txs.py
Labels: type:test

#704 feat(consume): `--fork` parameter, fix naming, refactoring
  src/pytest_plugins/consume/consume.py
  src/pytest_plugins/consume/decorator.py
  src/pytest_plugins/consume/direct/__init__.py
  src/pytest_plugins/consume/direct/test_direct.py
  src/pytest_plugins/consume/hive_simulators/__init__.py
  src/pytest_plugins/consume/hive_simulators/engine/__init__.py
  src/pytest_plugins/consume/hive_simulators/engine/test_via_engine.py
  src/pytest_plugins/consume/hive_simulators/rlp/__init__.py
  src/pytest_plugins/consume/hive_simulators/rlp/test_via_rlp.py
  src/pytest_plugins/pytest_hive/pytest_hive.py
Labels: type:refactor, type:feat

#708 feat(consume): Enhance timing data
  src/cli/pytest_commands.py
  src/pytest_plugins/consume/consume.py
  src/pytest_plugins/consume/hive_simulators/conftest.py
  src/pytest_plugins/consume/hive_simulators/engine/test_via_engine.py
  src/pytest_plugins/consume/hive_simulators/rlp/test_via_rlp.py
  src/pytest_plugins/consume/hive_simulators/timing.py
Labels: type:refactor, type:feat

#714 refactor(pytest|consume): re-structure and refine pytest & consume commands.
  pytest-framework.ini
  setup.cfg
  src/cli/pytest_commands.py
  src/cli/pytest_commands/__init__.py
  src/cli/pytest_commands/common.py
  src/cli/pytest_commands/consume.py
  src/cli/pytest_commands/fill.py
  src/cli/tests/test_pytest_fill_command.py
  src/pytest_plugins/consume/direct/test_via_direct.py
  src/pytest_plugins/help/help.py
  whitelist.txt
Labels: scope:pytest, type:refactor, scope:consume

#712 fix(consume,plugins): Fix suite duplication due to xdist, consume cli refactor
  docs/CHANGELOG.md
  pytest-framework.ini
  setup.cfg
  src/cli/pytest_commands.py
  src/cli/pytest_commands/__init__.py
  src/cli/pytest_commands/common.py
  src/cli/pytest_commands/consume.py
  src/cli/pytest_commands/fill.py
  src/cli/tests/test_pytest_fill_command.py
  src/pytest_plugins/consume/consume.py
  src/pytest_plugins/consume/direct/test_via_direct.py
  src/pytest_plugins/consume/hive_simulators/engine/conftest.py
  src/pytest_plugins/consume/hive_simulators/rlp/conftest.py
  src/pytest_plugins/help/help.py
  src/pytest_plugins/pytest_hive/pytest_hive.py
  whitelist.txt
Labels: type:bug, scope:pytest, type:refactor, type:feat, scope:consume

#622 feat(tests): use dynamic pre alloc within shanghai tests
  src/pytest_plugins/filler/pre_alloc.py
  tests/shanghai/eip3651_warm_coinbase/conftest.py
  tests/shanghai/eip3651_warm_coinbase/spec.py
  tests/shanghai/eip3651_warm_coinbase/test_warm_coinbase.py
  tests/shanghai/eip3855_push0/conftest.py
  tests/shanghai/eip3855_push0/spec.py
  tests/shanghai/eip3855_push0/test_push0.py
  tests/shanghai/eip3860_initcode/conftest.py
  tests/shanghai/eip3860_initcode/helpers.py
  tests/shanghai/eip3860_initcode/spec.py
  tests/shanghai/eip3860_initcode/test_initcode.py
  tests/shanghai/eip4895_withdrawals/conftest.py
  tests/shanghai/eip4895_withdrawals/spec.py
  tests/shanghai/eip4895_withdrawals/test_withdrawals.py
Labels: scope:tests, type:feat

#716 feat(filler): generate index
  docs/CHANGELOG.md
  src/pytest_plugins/filler/filler.py
  src/pytest_plugins/filler/tests/test_filler.py
Labels: type:feat

#721 feat(fw): use a metadata folder within fixtures
  docs/CHANGELOG.md
  src/cli/gen_index.py
  src/cli/tests/test_pytest_fill_command.py
  src/pytest_plugins/consume/consume.py
  src/pytest_plugins/filler/filler.py
  src/pytest_plugins/filler/tests/test_filler.py
Labels: type:feat, scope:fw

#725 fix(plugins/filler): Index generation concurrency issue
  docs/CHANGELOG.md
  src/cli/pytest_commands/fill.py
  src/pytest_plugins/filler/filler.py
  src/pytest_plugins/filler/tests/test_filler.py
Labels: type:bug
